min_objects: 3
max_objects: 4
min_object_size: 0.015
max_object_size: 0.02
sample_size: true
sample_colour: true
color_noise: 0.1
shapes:
  - cube
colours:
  - green
  - blue
textures:
  - plain
  - stary
  - dotted
