min_objects: 4
max_objects: 6
min_object_size: 0.015
max_object_size: 0.016
sample_size: true
sample_colour: true
color_noise: 0.1
shapes:
  - cube
colours:
  - green
  - blue
  - red
  - yellow 
  - cyan 
  - magenta
textures:
  - plain
  - stary
  - dotted