defaults:
  - actuator_config: shadow_hand 
  - sensor_config: shadow_hand
  - controller_config: shadow_hand

end_effector:
  _target_: mujoco_robot_environments.models.end_effectors.shadow_hand.ShadowHand
  mjcf_path: "../submodules/mujoco_menagerie/shadow_hand/right_hand.xml"
  actuator_config: ${robots.end_effector.actuator_config}
  sensor_config: ${robots.end_effector.sensor_config}
  controller_config: ${robots.end_effector.controller_config}
