# initializers for robot and props
initializers:
  seed: 1
  workspace:
    min_pose: [0.35, -0.4, 0.43]
    max_pose: [0.55, 0.4, 0.435]
  gripper:
    min_pose: [0.4, -0.0, 0.7, 3.14, 0.0, 0.0]
    max_pose: [0.5, 0.0, 0.7, 3.14, 0.0, 0.0]
